<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>snort</string>
		<string>rules</string>
	</array>
	<key>name</key>
	<string>Snort</string>
	<key>scopeName</key>
	<string>source.snort</string>
	<key>patterns</key>
    <array>
        <!-- Rule Header -->
        <!-- Action -->
        <dict>
            <key>name</key>
            <string>variable.language.action</string>
            <key>match</key>
            <string>\b(alert|log|pass|activate|dynamic|drop|reject|sdrop)\b</string>
        </dict>
        <!-- Protocol -->
        <dict>
            <key>name</key>
            <string></string>
            <key>match</key>
            <string>\b(tcp|udp|icmp|ip)\b</string>
        </dict>
        <!-- IP Addresses -->
        <dict>
            <key>name</key>
            <string></string>
            <key>match</key>
            <string>([0-9]{1,3}\.){3}([0-9]{1,3}|0\/[0-9]{1,2})</string>
        </dict>
        <!-- Port Numbers -->
        <dict>
            <key>name</key>
            <string></string>
            <key>match</key>
            <string></string>
        </dict>
        <!-- Direction -->
        <dict>
            <key>name</key>
            <string></string>
            <key>match</key>
            <string></string>
        </dict>
        <!-- Activate -->
        <dict>
            <key>name</key>
            <string></string>
            <key>match</key>
            <string></string>
        </dict>
        <!-- Dynamic -->
        <dict>
            <key>name</key>
            <string></string>
            <key>match</key>
            <string></string>
        </dict>
        <!-- Rule Options -->
        <dict>
            <key>name</key>
            <string>keyword.other.option.snort</string>
            <key>match</key>
            <string>(msg|content|reference|classtype|priority|sid|rev|nocase|offset|pcre):</string>
        </dict>
        <!-- General -->
        <!-- Double Quoted Strings -->
        <dict>
            <key>name</key>
            <string>string.quoted.double.snort</string>
            <key>match</key>
            <string>\".*\"</string>
        </dict>
		<!-- Variables : Any word that starts with '$' -->
        <dict>
			<key>name</key>
			<string>variable.parameter.snort</string>
			<key>match</key>
            <!-- variables must be all caps and numbers -->
			<string>(\$)[A-Z0-9_]+\b</string>
		</dict>
        <dict>
            <key>name</key>
            <string>invalid.illegal.variable.snort</string>
            <key>match</key>
            <!-- variables with lowercase letters in them aren't allowed -->
            <string>(\$)[A-Z0-9_]*[a-z]*[A-Z0-9_]*\b</string>
    </array>
	<key>smartTypingPairs</key>
	<array>
		<array>
			<string>"</string>
			<string>"</string>
		</array>
		<array>
			<string>(</string>
			<string>)</string>
		</array>
		<array>
			<string>{</string>
			<string>}</string>
		</array>
		<array>
			<string>[</string>
			<string>]</string>
		</array>
		<array>
			<string><</string>
			<string>></string>
		</array>
		<array>
			<string>/*</string>
			<string>*/</string>
		</array>
	</array>
	<key>highlightPairs</key>
	<array>
		<array>
			<string>"</string>
			<string>"</string>
		</array>
		<array>
			<string>(</string>
			<string>)</string>
		</array>
		<array>
			<string>{</string>
			<string>}</string>
		</array>
		<array>
			<string>[</string>
			<string>]</string>
		</array>
		<array>
			<string><</string>
			<string>></string>
		</array>
	</array>
</dict>
</plist>